directories:
  input: './input'
  output:
    content: './output/content'
    files: './output/files'
    images: './output/images'
    xml: './output/xml'

ids:
  homepage: 2
  images: 51
  files: 52
  safety: 100

db: 3
