directories:
  input: './input'
  output:
    content: './output/content'
    files: './output/files'
    images: './output/images'
    xml: './output/xml'

ids:
  homepage: 2
  images: '1b26c0454b09bb49dfb1b9190ffd67cb'
  files: '0b113a208f7890f9ad3c24444ff5988c'
  safety: 100

db: 3
