directories:
  input: './input'
  output:
    content: './output/content'
    files: './output/files'
    images: './output/images'
    xml: './output/xml'
  dbs: './database_exports'

ids:
  homepage: '547cc4ebe61632474a33700a26e8b21b'
  images: 'e7ff633c6b8e0fd3531e74c6e712bead'
  files: '732a5acd01b51a6fe6eab448ad4138a9'
  start: 10000

db: 3
